os: linux
dist: bionic
arch: ppc64le
sudo: required
language: go

go: "1.15.x"

install:
  - printf "deb https://oplab9.parqtec.unicamp.br/pub/repository/debian/ ./" >> /etc/apt/sources.list
  - wget https://oplab9.parqtec.unicamp.br/pub/key/openpower-gpgkey-public.asc
  - sudo apt-key add openpower-gpgkey-public.asc
  - sudo apt update
  - sudo apt install -y golang-go libassuan-dev libdevmapper-dev libglib2.0-dev libc6-dev \
   libgpg-error-dev libseccomp-dev libsystemd-dev libselinux1-dev pkg-config \
   libudev-dev software-properties-common gcc btrfs-progs runc conmon crun

script:
  - git clone https://github.com/cri-o/cri-o.git
  - cd cri-o/
  - make
  - cd bin/
  - ./crio --version
